# Generated by Django 6.0.3 on 2026-04-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duke_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Claass',
            new_name='Class',
        ),
    ]
