# Generated by Django 6.0.3 on 2026-05-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duke_app', '0002_rename_claass_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount_due',
            field=models.PositiveIntegerField(default=15000),
        ),
    ]
